services:
  jupyter:
    build: ./jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./data/300_stock_headlines.csv:/home/jovyan/data/300_stock_headlines.csv
      - ./GettingStarted.ipynb:/home/jovyan/GettingStarted.ipynb
  vecsim:
    image: redislabs/redisearch:feature-vecsim
    ports:
      - "6379:6379"
