FROM jupyter/minimal-notebook

RUN pip install grpcio numpy pandas sentence-transformers ipywidgets torch Pillow img2vec_pytorch 
RUN pip install transformers tensorflow 
RUN pip install redis
RUN mkdir /home/jovyan/data